modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="abdibs_mod"
version="1.0.0"
displayName="Abdib's Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="TheGoldenPig, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.abdibs_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.abdibs_mod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

